/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {},
    fontFamily: {
      Jakarta: ["PlusJakartaSans-Regular", "sans-serif"],
      JakartaBold: ["PlusJakartaSans-Bold", "sans-serif"],
      JakartaBoldItalic: ["PlusJakartaSans-BoldItalic", "sans-serif"],
      JakartaExtraBold: ["PlusJakartaSans-ExtraBold", "sans-serif"],
      JakartaExtraBoldItalic: ["PlusJakartaSans-ExtraBoldItalic", "sans-serif"],
      JakartaExtraLight: ["PlusJakartaSans-ExtraLight", "sans-serif"],
      JakartaExtraLightItalic: ["PlusJakartaSans-ExtraLightItalic", "sans-serif"],
      JakartaItalic: ["PlusJakartaSans-Italic", "sans-serif"],
      JakartaLight: ["PlusJakartaSans-Light", "sans-serif"],
      JakartaLightItalic: ["PlusJakartaSans-LightItalic", "sans-serif"],
      JakartaMedium: ["PlusJakartaSans-Medium", "sans-serif"],
      JakartaMediumItalic: ["PlusJakartaSans-MediumItalic", "sans-serif"],
      JakartaSemiBold: ["PlusJakartaSans-SemiBold", "sans-serif"],
      JakartaSemiBoldItalic: ["PlusJakartaSans-SemiBoldItalic", "sans-serif"],
    },
    colors: {
      white: 'var(--color-white)',
      black: 'var(--color-black)',
      
      background: 'var(--color-background)',
      foreground: 'var(--color-foreground)',
      primary: 'var(--color-primary)',
      secondary: 'var(--color-secondary)',
      accent: 'var(--color-accent)',

      textPrimary: 'var(--color-text-primary)',
      textSecondary: 'var(--color-text-secondary)',
      faintText: 'var(--color-faint-text)',

      buttonPrimary: 'var(--color-button-primary)',
      buttonSecondary: 'var(--color-button-secondary)',
      buttonTextPrimary: 'var(--color-button-text-primary)',
      buttonTextSecondary: 'var(--color-button-text-secondary)',

      iconPrimary: 'var(--color-icon-primary)',
      iconSecondary: 'var(--color-icon-secondary)',
      iconFaint: 'var(--color-icon-faint)',

      border: 'var(--color-border)',
      borderFaint: 'var(--color-border-faint)',
      shadowSm: 'var(--color-shadow-sm)',
      shadowMd: 'var(--color-shadow-md)',
      shadowLg: 'var(--color-shadow-lg)',

      inputBackground: 'var(--color-input-background)',
      inputText: 'var(--color-input-text)',
      inputPlaceholder: 'var(--color-input-placeholder)',
      inputBorder: 'var(--color-input-border)',
      inputFocusBorder: 'var(--color-input-focus-border)',
      inputFocusBackground: 'var(--color-input-focus-background)',
      inputFocusText: 'var(--color-input-focus-text)',
      inputFocusPlaceholder: 'var(--color-input-focus-placeholder)',
      inputFocusShadow: 'var(--color-input-focus-shadow)',

      success: 'var(--color-success)',
      error: 'var(--color-error)',
      danger: 'var(--color-danger)',
      warning: 'var(--color-warning)',
      info: 'var(--color-info)',
    },
  },
  plugins: [],
};